name: Show Tag Reference

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  new-tag-notification:
    uses: code-fiddle/github-actions-playground/.github/workflows/template-release-slack-notification.yaml@main
    secrets:
      slack_url: ${{ secrets.SLACK_URL }}
