name: Get Tag Reference
# https://github.com/camunda-cloud/console/releases/tag/1.3.3-rc2
env:
  GH_ORG: urban-zoo
  GH_PROJECT: github-actions-playground

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo https://github.com/${{ env.GH_ORG }}/${{ env.GH_PROJECT }}//${{ env.RELEASE_VERSION }}
