name: Show Tag Reference

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  new-tag-notification:
    uses: code-fiddle/github-actions-playground/.github/workflows/template-release-slack-notification.yaml@main
    secrets:
      slack_url: ${{ secrets.SLACK_URL }}
      # - name: Set output
      #   id: vars
      #   run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      # - name: Check output
      #   env:
      #     RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      #   run: |
      #     echo $RELEASE_VERSION
      #     echo ${{ steps.vars.outputs.tag }}
      #     echo https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}
      #     curl -X POST \
      #          "${{ secrets.SLACK_URL }}" \
      #          -H 'Content-type: application/json' \
      #          --data '{"text":"New Release of ${{ github.repository }}", "attachments": [ { "title": "Release Notes for ${{ env.RELEASE_VERSION }}", "title_link": "https://github.com/${{ github.repository }}/releases/tag/${{ env.RELEASE_VERSION }}" } ] }'
